services:
  frontend:
    build: 
      context: ./task-flow
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./mock-server:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "4000:4000"